name: gen_type_value
description: description
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^5.8.0
  build: ^2.3.0
  gen_type_value_annotation:
    path: ../gen_type_value_annotation
  source_gen: ^1.2.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
